accounts/urls.py
from django.urls import path
from . import views
 
app_name = 'accounts'
 
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('', views.index, name='index'),
]

equipment_management/urls.py
from django.urls import path
from . import views

app_name = 'equipment'

urlpatterns = [
  path('month/', views.MonthCalendar.as_view(), name='month'),
  path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
  path('add_band/', views.add_band, name='add_band'),
  path('add_schedule/', views.add_schedule, name='add_schedule'),
  path('show_band_list', views.show_band_list, name='show_band_list'),
  path('updete_schedule/<int:pk>/', views.update_schedule, name='update_schedule'),
  path('delete_schedule/<int:pk>/', views.delete_schedule, name='delete_schedule'),
  path('delete_band/<int:pk>/', views.delete_band, name='delete_band'),
  path('schedule_by_band/<int:pk>', views.schedule_by_band, name='schedule_by_band'),
  path('day_schedule/<int:year>/<int:month>/<int:day>', views.day_schedule, name='day_schedule'),
]

pde_reservation_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipment_management/', include('equipment_management.urls')),
    path('accounts/', include('accounts.urls')),
]

equipment_management/models.py
from django.db import models
from django.utils import timezone
import datetime


def nine_hours_hence():
    return timezone.now() + timezone.timedelta(hours=9)

def two_hours_hence():
    return timezone.now() + timezone.timedelta(hours=11)

class Band(models.Model): 
  band_name = models.CharField(max_length=255,
                               verbose_name="Band's Name",
                               unique=True,
                               )
  responsible_person_name = models.CharField(max_length=255,
                                             verbose_name="Band Master's Name")
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
      return self.band_name


class Schedule(models.Model):
  band_id = models.ForeignKey(Band, on_delete=models.CASCADE)
  pa_name = models.CharField(max_length=255, verbose_name='PA担当者名')
  active_date = models.DateField(default=timezone.now, verbose_name='予約日')
  start_at = models.TimeField(default= nine_hours_hence(), verbose_name='開始時間')
  end_at = models.TimeField(default=two_hours_hence, verbose_name='終了時間')
  text = models.TextField(blank=True, verbose_name='備考欄')
  created_at = models.DateTimeField(auto_now=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.band_id.band_name + ': ' +  str(self.active_date) + ' ' + str(self.start_at) + ' - ' + str(self.end_at)

  def is_avaiable(self):
    today = datetime.date.today()
    current_time = datetime.datetime.now().time()
    if today < self.active_date:
      return True
    elif (today == self.active_date) and (current_time < self.start_at):
      return True
    else:
      return False

equipment_management/forms.py
from django import forms
from .models import Band, Schedule
import datetime


class DateInput(forms.DateInput):
    input_type = 'date'

class BandCreateForm(forms.ModelForm):

  class Meta:
    model = Band
    fields = ('band_name', 'responsible_person_name')


class ScheduleCreateForm(forms.ModelForm):

  class Meta:
    model = Schedule
    fields = '__all__'
    widgets = {
        'active_date': DateInput(),
    }

  def clean(self):
    start_at = self.cleaned_data['start_at']
    end_at = self.cleaned_data['end_at']
    active_date = self.cleaned_data['active_date']
    schedules = Schedule.objects.filter(active_date=active_date).exclude(id=self.instance.id)
    for schedule in schedules:
      if not ((start_at >= schedule.end_at) or (end_at <= schedule.start_at)):
        raise forms.ValidationError(
          '指定された時刻には既に予約が入っています'
          )

    if end_at <= start_at:
      raise forms.ValidationError(
        '終了時間は、開始時間よりも後にしてください'
        )
  
    if active_date < datetime.date.today():
      raise forms.ValidationError(
        '今日より前の日付に予約はできません'
        )


    return self.cleaned_data

  # def clean_end_at(self):
  #   start_at = self.cleaned_data['start_at']
  #   end_at = self.cleaned_data['end_at']

  #   if end_at <= start_at:
  #     raise forms.ValidationError(
  #       '終了時間は、開始時間よりも後にしてください'
  #       )
  #   return end_at

  # def clean_active_date(self):
  #   active_date = self.cleaned_data['active_date']
  #   print(active_date, datetime.date.today())
  #   if active_date < datetime.date.today():
  #     raise forms.ValidationError(
  #       '今日より前の日付に予約はできません'
  #       )
  #   return active_date

equipment_management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Band, Schedule
from .forms import BandCreateForm, ScheduleCreateForm
from . import mixins
from django.views import generic
import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator


@login_required
def add_band(request):
  form = BandCreateForm(request.POST or None)
  if request.method == 'POST' and form.is_valid():
    form.save()
    return redirect('equipment:show_band_list')
  context = {
    'form' : BandCreateForm(),
    'title' : 'バンド登録',
  }
  if request.method == 'POST' and not form.is_valid():
    context['error_message'] = "※ 既に登録されたバンド名が入力されています。"
  return render(request, 'equipment_management/band_form.html', context)

@login_required
def add_schedule(request):
  form = ScheduleCreateForm(request.POST or None)
  if request.method == 'POST' and form.is_valid():
    form.save()
    return redirect('equipment:month')
  context = {
    'form' : ScheduleCreateForm(),
    'title' : '機材予約',
  }
  if request.method == 'POST' and not form.is_valid():
    context['error_message'] = "※ 既にその時間には予約が入っているか、時間の入力に誤りがあります"
  return render(request, 'equipment_management/band_form.html', context)

@login_required
def show_band_list(request):
  context ={
      'bands' : Band.objects.all(),
  }
  return render(request, 'equipment_management/band_list.html', context)

@login_required
def update_schedule(request, pk):
  schedule = get_object_or_404(Schedule, pk=pk)

  form = ScheduleCreateForm(request.POST or None, instance=schedule)
  if request.method == 'POST' and form.is_valid():
    form.save()
    return redirect('equipment:month')

  context = {
      'form' : form,
      'title' : '予約の変更',
  }
  return render(request, 'equipment_management/band_form.html', context)

@login_required
def delete_schedule(request, pk):
  schedule = get_object_or_404(Schedule, pk=pk)
  if request.method == 'POST':
    schedule.delete()
    return redirect('equipment:month')

  context = {
    'schedule': schedule,
  }
  return render(request, 'equipment_management/schedule_confirm_delete.html', context)

@login_required
def delete_band(request, pk):
  band = get_object_or_404(Band, pk=pk)
  if request.method == 'POST':
      band.delete()
      return redirect('equipment:show_band_list')

  context = {
      'band': band,
  }
  return render(request, 'equipment_management/band_confirm_delete.html', context)

@login_required
def schedule_by_band(request, pk):
  band_name = Band.objects.get(pk=pk)
  context = {
      'band_name' : band_name,
      'schedules' : Schedule.objects.filter(band_id=band_name).order_by('-active_date'),
  }
  return render(request, 'equipment_management/schedule_by_band.html', context)

@login_required
def day_schedule(request, year, month, day):
  target_date = datetime.date(year, month, day)
  context ={
      'schedules' : Schedule.objects.filter(active_date=target_date).order_by('start_at'),
      'target_date' : target_date,
  }
  return render(request, 'equipment_management/day_schedule.html', context)

@method_decorator(login_required, name='dispatch')
class MonthCalendar(mixins.MonthCalendarMixin, generic.TemplateView):
    """月間カレンダーを表示するビュー"""
    template_name = 'equipment_management/month.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        today_date = datetime.date.today()
        context['schedules'] = Schedule.objects.filter(active_date=today_date).order_by('start_at')
        context['today'] = today_date
        return context

equipment_management/templates/equipment_management/band_confirm_delete.html
{% extends 'equipment_management/base.html' %}

{% block content %}
<form action="" method="POST">
    <table class="table">
      <tr>
        <th>バンド名</th>
        <td>{{ band.band_name }}</td>
      </tr>
        <th>バンドマスター</th>
        <td>{{ band.responsible_person_name }}</td>
      </tr>
    </table>
  <p>このバンドを削除します</p>
  <p>このバンドの予約も全て削除されますが、よろしいですか？</p>
  <button type="submit" class="btn btn-primary">削除</button>
  {% csrf_token %}
</form>
{% endblock %}

equipment_management/templates/equipment_management/band_form.html
{% extends 'equipment_management/base.html' %}

{% block content %}


{% if error_message %}
  <br>
  <div class="error-message alert alert-danger">
    {{ error_message }}
  </div>
  <br>
{% endif %}

<h4><i class="fas fa-file-import"></i> {{ title }}</h4>
<br>
<div class="container">
  <form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
      <div class="form-group row">
        <label for="{{ field.id_for_label }}"
          class="col-sm-2 col-form-label">{{ field.label_tag }}</label>
        <div class="col-sm-8">
          {{ field }}
          {{ field.errors }}
        </div>
      </div>
    {% endfor %}
  <button type="submit" class="btn btn-primary">登録</button>
  {% csrf_token %}
  </form>
</div>

{% endblock %}

{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>

    <script>
      $(function () {
        // timedropper
        $("#id_start_at").timeDropper({
            format: "H:mm",
            setCurrentTime: false,
        });

        $("#id_end_at").timeDropper({
            format: "H:mm",
            setCurrentTime: false,
        });

      });
    </script>
{% endblock %}

equipment_management/templates/equipment_management/band_list.html
{% extends 'equipment_management/base.html' %}

{% block content %}
<br>
<h4><i class="fas fa-microphone"></i> PDE Band List</h4>
<br>

<table class="table">
  <thead>
    <tr>
      <th>Band Names</th>
      <th>Band Masters</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for band in bands %}
    <tr>
      <td><a href="{% url 'equipment:schedule_by_band' band.pk %}">{{ band.band_name }}</a></td>
      <td>{{ band.responsible_person_name }}</td>
      <td>
        <a href="{% url 'equipment:delete_band' band.pk %}">
            <button type="button" class="btn btn-danger" style="font-size: 10px;">削除</button>
        </a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

equipment_management/templates/equipment_management/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <title>PDE機材予約システム</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <!-- FontAwesone -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'equipment:month' %}">PDE機材予約システム</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'equipment:month' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'equipment:show_band_list' %}">Bands</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'equipment:add_schedule' %}">機材予約</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'equipment:add_band' %}">バンド登録</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
          </ul>
        </div>
      </nav>
      {% block content %}
      {% endblock %}
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
    <br>
    <br>
    <br>
    <hr>
    <br>
    <hr>
    <footer class="footer">
        <br>
        <div class="copyright text-center">
          <p>© 2019 - Shohei Hayashi, Kento Nakahata</p>
        </div>
        <div class="sns text-center">
          <a>Contact with Hayashi : </a>
          <a href="https://twitter.com/Ring_Sho" class="tw"><i class="fab fa-twitter"></i></a>
          <a href="https://www.instagram.com/shoooohei_884/" class="insta"><i class="fab fa-instagram"></i></a>
        </div>
        <div class="sns text-center">
          <a>Contact with Nakahata : </a>
          <a href="https://twitter.com/masyuo64" class="tw"><i class="fab fa-twitter"></i></a>
          <a href="https://www.instagram.com/kento64kinoko/" class="insta"><i class="fab fa-instagram"></i></a>
        </div>
        <br>
      </footer>
  </body>
</html>

equipment_management/templates/equipment_management/day_schedule.html
{% extends 'equipment_management/base.html' %}

{% block content %}

<br>
<h4><i class="fas fa-microphone"></i> {{ target_date }}の予約一覧</h4>
<br>
{% for schedule in schedules %}
<div class="card">
    <div class="card-body">
      <h6 class="card-title font-weight-bold">
        <a href="{% url 'equipment:schedule_by_band' schedule.band_id.id %}">{{ schedule.band_id }}</a>
      </h6>
      <p class="card-text font-weight-bold">予約日時</p>
      <p class="card-text">{{ schedule.active_date }} {{ schedule.start_at }} - {{ schedule.end_at }}</p>
      <p class="card-text font-weight-bold">備考</p>
      <div class='test'>
        <p class="card-text text-break">{{ schedule.text }}</p>
      </div>
      <br>
      {% if schedule.is_avaiable %}
      <a href="{% url 'equipment:update_schedule' schedule.pk %}">
          <button type="button" class="btn btn-success btn-xs" style="font-size: 10px;">予約変更</button>
      </a>
      <a href="{% url 'equipment:delete_schedule' schedule.pk %}">
        <button type="button" class="btn btn-danger btn-xs" style="font-size: 10px;">予約取消</button>
      </a>
      {% endif %}
    </div>
  </div>
{% endfor %}
{% endblock %}

equipment_management/templates/equipment_management/month.html
{% extends 'equipment_management/base.html' %}

{% block content %}

<br>
<h4><i class="fas fa-calendar-week"></i> 予約スケジュール</h4>
<br>

<a href="{% url 'equipment:month' month_previous.year month_previous.month %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'equipment:month' month_next.year month_next.month %}">次月</a>

<table class="table">
  <thead>
    <tr>
      {% for w in week_names %}
        <th>{{ w }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for week in month_days %}
      <tr>
        {% for day in week %}
          {% if now == day %}
            <td class="table-success">
          {% else %}
            <td>
          {% endif %}

          {% if month_current.month != day.month %}
            <a href="{% url 'equipment:day_schedule' day.year day.month day.day %}">{{ day | date:"m/d" }}</a>
          {% else %}
            <a href="{% url 'equipment:day_schedule' day.year day.month day.day %}">{{ day.day }}</a>
          {% endif %}

            </td>
        {% endfor %}
      </tr>
    {% endfor %}
  </tbody>
</table>

<br>
<br>
<br>
<br>
<br>

<h4><i class="fas fa-microphone"></i> 本日({{ today }})の予約一覧</h4>
<br>
{% for schedule in schedules %}
<div class="card" id='sche'>
    <div class="card-body">
      <h6 class="card-title font-weight-bold">
        <a href="{% url 'equipment:schedule_by_band' schedule.band_id.id %}">{{ schedule.band_id }}</a>
      </h6>
      <p class="card-text font-weight-bold">予約日時</p>
      <p class="card-text">{{ schedule.active_date }} {{ schedule.start_at }} - {{ schedule.end_at }}</p>
      <p class="card-text font-weight-bold">備考</p>
      <div class='test'>
        <p class="card-text text-break">{{ schedule.text }}</p>
      </div>
      <br>
      {% if schedule.is_avaiable %}
      <a href="{% url 'equipment:update_schedule' schedule.pk %}">
          <button type="button" class="btn btn-success btn-xs" style="font-size: 10px;">予約変更</button>
      </a>
      <a href="{% url 'equipment:delete_schedule' schedule.pk %}">
        <button type="button" class="btn btn-danger btn-xs" style="font-size: 10px;">予約取消</button>
      </a>
      {% endif %}
    </div>
  </div>
{% endfor %}

{% endblock %}

equipment_management/templates/equipment_management/schedule_by_band.html
{% extends 'equipment_management/base.html' %}

{% block content %}
<br>
<h4><i class="fas fa-microphone"></i> {{ band_name }}の予約一覧</h4>
<br>

{% for schedule in schedules %}
<div class="card">
    <div class="card-body">
      <h6 class="card-title font-weight-bold">
        <a href="{% url 'equipment:schedule_by_band' schedule.band_id.id %}">{{ schedule.band_id }}</a>
      </h6>
      <p class="card-text font-weight-bold">予約日時</p>
      <p class="card-text">{{ schedule.active_date }} {{ schedule.start_at }} - {{ schedule.end_at }}</p>
      <p class="card-text font-weight-bold">備考</p>
      <div class='test'>
        <p class="card-text text-break">{{ schedule.text }}</p>
      </div>
      <br>
      {% if schedule.is_avaiable %}
        <a href="{% url 'equipment:update_schedule' schedule.pk %}">
            <button type="button" class="btn btn-success btn-xs" style="font-size: 10px;">予約変更</button>
        </a>
        <a href="{% url 'equipment:delete_schedule' schedule.pk %}">
          <button type="button" class="btn btn-danger btn-xs" style="font-size: 10px;">予約取消</button>
        </a>
      {% endif %}
    </div>
  </div>
{% endfor %}

{% endblock %}

equipment_management/templates/equipment_management/schedule_confirm_delete.html
{% extends 'equipment_management/base.html' %}

{% block content %}
<br>
<h4><i class="fas fa-trash-alt"></i> 予約取消</h4>
<br>

<form action="" method="POST">
    <table class="table">
      <tr>
        <th>バンド名</th>
        <td>{{ schedule.band_id }}</td>
      </tr>
      <tr>
        <th>Start at</th>
        <td>{{ schedule.start_at }}</td>
      </tr>
      <tr>
        <th>End at</th>
        <td>{{ schedule.end_at }}</td>
      </tr>
      <tr>
        <th>備考</th>
        <td>{{ schedule.text }}</td>
      </tr>
    </table>
  <p>この予約を取り消します</p>
  <button type="submit" class="btn btn-danger">削除</button>
  {% csrf_token %}
</form>
{% endblock %}