accounts/urls.py
from django.urls import path
from . import views
 
app_name = 'accounts'
 
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('', views.index, name='index'),
]

equipment_management/urls.py
from django.urls import path
from . import views

app_name = 'equipment'

urlpatterns = [
  path('month/', views.MonthCalendar.as_view(), name='month'),
  path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
  path('add_band/', views.add_band, name='add_band'),
  path('add_schedule/', views.add_schedule, name='add_schedule'),
  path('show_band_list', views.show_band_list, name='show_band_list'),
  path('updete_schedule/<int:pk>/', views.update_schedule, name='update_schedule'),
  path('delete_schedule/<int:pk>/', views.delete_schedule, name='delete_schedule'),
  path('delete_band/<int:pk>/', views.delete_band, name='delete_band'),
  path('schedule_by_band/<int:pk>', views.schedule_by_band, name='schedule_by_band'),
  path('day_schedule/<int:year>/<int:month>/<int:day>', views.day_schedule, name='day_schedule'),
]

pde_reservation_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('equipment_management/', include('equipment_management.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import(
    AuthenticationForm
)
 
class LoginForm(AuthenticationForm):
    #ログオンフォームの定義
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fields in self.fields.values():
            fields.widget.attrs['class'] = 'form-control'
            fields.widget.attrs['placeholder']= fields.label

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(
    LoginView, LogoutView
)
 
from . forms import LoginForm
 
class Login(LoginView):
    #ログインページ
    form_class = LoginForm
    template_name = 'accounts/login.html'
 
 
class Logout(LoginRequiredMixin, LogoutView):
    #ログアウトページ
    template_name = 'accounts/login.html'
 
 
def index(request):
    
    return render(request, 'accounts/index.html')

accounts/templates/accounts/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <title>PDE機材管理</title>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'equipment:month' %}">PDE機材予約システム</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'equipment:month' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'equipment:show_band_list' %}">Bands</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'equipment:add_band' %}">バンド登録</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
        </ul>
      </div>
    </nav>
 
    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>
 
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
            <br>
            <br>
            <br>
            <hr>
            <br>
            <footer class="footer">
                <br>
                <div class="copyright text-center">
                  <p>© 2019 - Shohei Hayashi, Kento Nakahata</p>
                </div>
                <div class="sns text-center">
                  <a>Contact with Hayashi : </a>
                  <a href="https://twitter.com/Ring_Sho" class="tw"><i class="fab fa-twitter"></i></a>
                  <a href="https://www.instagram.com/shoooohei_884/" class="insta"><i class="fab fa-instagram"></i></a>
                </div>
                <div class="sns text-center">
                  <a>Contact with Nakahata : </a>
                  <a href="" class="tw"><i class="fab fa-twitter"></i></a>
                  <a href="#" class="insta"><i class="fab fa-instagram"></i></a>
                </div>
                <br>
              </footer>
</body>
</html>

accounts/templates/accounts/index.html
{% extends "accounts/base.html" %}
{% block content %}
ログアウトしました。
{% endblock %}

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}
{% block content %}
<br>
<div class="col-md-6 offset-md-3">
  <h2>ログイン画面</h2>
</div>
<br>
<form action="" method="POST">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-body">
        {% for field in form %}
          {{ field }}
          <hr>
　　     {% endfor %}

　　　　  {% for error in form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            <p>{{ error }}</p>
          </div>
　　　　　{% endfor %}
        <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
        <input type="hidden" name="next" value="{{ next }}" />
        {% csrf_token %}
      </div>
    </div>
  </div>
</form>
{% endblock %}